# Generated by Django 4.2.4 on 2023-08-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField(default=0.0)),
                ('ingredients', models.TextField(blank=True)),
                ('with_beef', models.BooleanField(default=False)),
                ('with_chicken', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
